name: WelcomePro
main: net.richardsprojects.welcomepro.WelcomePro
version: 2.0.0
commands:
   welcomepro:
      description: This is the main command of the plugin
      usage: /<command>
      permission: WelcomePro.admin
      permission-message: You don't have <permission>
      aliases: wp